sudo: false
language:
  - ruby
dist:
  - xenial
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
rvm:
  - 2.6.5
services:
  - postgresql
addons:
  postgresql: "9.6"
notifications:
  - false
before_install:
  - sudo apt-get update  
before_script:  
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:create
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rails webpacker:install
  - bundle exec rails webpacker:compile
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: "J9aV8MnioGUTXm4pdyojbrYjFwja5j8ClvGou6e/h/QDot9nZ23KmrDzKi5qo+ICA2MBSLmxpwzHZBVU0hE4zZLEfXFerJix3wVcFEq5XASwMybYYDC9dEUK7hLJQT3iw6DVNF9R0gXFIINuceQRSwSNb2rHGLDYTHxdp2DfYE4h5yjMY2uhXvy4+bUFbmQdP7Xm9yPM/o73YOeed0GiRcNLyUhV57CL4DN2jm9J/7zId2JHTfVfNpOmc14Dt/Cet1sC+CQwBs+kW2PAN25TyJQKrMXpJEUDbHLfYiVekULznzGfqOzBq+u1KmgkcHCgXvDXpg8wawe5NnS5dFUcbl0DxNa7gbwi5I9oE8L9/e58q0hLZEAXdY7NJgAnwOTmcr+kCkJjV5grBbLo/fC4Tu98BTIT3dmfqFIKuB8RrGfUurrgg+MQcnLMzWZcDNjScFaBoRkniglgkdue3F/3uwCoIbT/+e37sdb31CzKcT4LG5o2TmNumrOqFD1DgLr4UC7zzs7+cbnwv89dWvKnUbdW9PLOPe6O7swJ8ebVeYaj6rF7Swa5s0wEo7UCT50nurFgnlJO3SHtTrcJka+wCSeZ+/9QFg8fu4oQ42leZ4HoZgIRbbukSRlGrkfYThQ9R8z2I+9iiGNBv2WtPiuyE4xEpaFKYyGk0sfMw932394="
  app: cc-balance-tracker
  on:
    repo: tflem/cc-balance-tracker
    branch: master
  run:
    - rake db:migrate
