sudo: false
language:
  - ruby
dist:
  - xenial
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
rvm:
  - 2.6.5
services:
  - postgresql
addons:
  postgresql: "9.6"
notifications:
  - false
before_install:
  - sudo apt-get update  
before_script:  
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:create
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rails webpacker:install
  - bundle exec rails webpacker:compile
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: cj5oaR4kObuk/9Ik09SewuSWeAWh0SwoCWV233KfBf2veLT9F2Ah/XNofB0twVvwM8EiyZ8/6H0Yta48Fb/mFOGgu0+vD7jph3Y3veZy8JYLEFMS8ewek1vhx/TvfbBfL0Ek3s00lDS+9oNkWYgacDTvoiaIqXKMhXPjYINW6LVZ/kZGTwMEYkVQLuUOr8gO29OLxw1rPaOgdmRz2FOTJS95R3w3N3qkjnIisFsBFMBmIC/Do8JKc81HUUvUrGsQzYrKEUmtID3Jk1LMoKWeDoL/kcXZd+gDOc5nzBF6msKWNpW4+U0qc09rACKkUqDUTSa5ycHlDlNExCQ5xXJCwhwunOKGjUzxRmXc4ocLwcWcu0B7ShH3T4/5TlhZcAw7o3FFqn75C6O0m/ScCgmYmU6wgDrnaiImIvHJlS4MbjlQxGfJLGWyrkYb7uM4pmjbczgp1yBuZxii3xui3oFyOMKJ98GwV+sBe6e5enVCNqxvNVqwF20aw735wyWd5xkaKSwHvKpLdjQ0+VbMGHjlziwgV3s4zTSNa0GWx0krYrc6TRhkUr+bbfIkts7whvNeIVlBpEEZhVBRxqtBoVL0tf+rLnbwRSDq8qob1Oz7lJV0Dnca0SJutJ/uK8UKgpdVNTN8FrJRYyLtQtSgDLsbWP7uHEuq4AsukCzEjQ4hJ7w=
  app: cc-balance-tracker
  on:
    repo: tflem/cc-balance-tracker
    branch: master
  run:
    - rake db:migrate
